name: CronJob - Optimism Mainnet
on:
  schedule:
    - cron: "5,35 16-23,0-4 * * *" # “At minute 5 and 35 past every hour from 16 through 23 and every hour from 0 through 4.”
  push:
env:
  CHAIN_ID: 10
  PRIZE_POOL_ADDRESS: "0xf35fe10ffd0a9672d0095c435fd8767a7fe29b55"
  OUTPUT_DIRECTORY_NAME: "winners/vaultAccounts"
  CLI_VERSION: "2.0.8"
  JSON_RPC_URL: ${{ secrets.OPTIMISM_MAINNET_RPC_URL }}
  CONTRACT_JSON_URL: 'https://raw.githubusercontent.com/GenerationSoftware/pt-v5-mainnet/396f04daedc5a38935460ddf47d2f10e9ac1fec6/deployments/optimism/contracts.json'
  SUBGRAPH_URL: 'https://api.studio.thegraph.com/query/63100/pt-v5-optimism/version/latest?source=pooltogether'
  REMOTE_STATUS_URL: 'https://raw.githubusercontent.com/GenerationSoftware/pt-v5-winners/refs/heads/main/winners/vaultAccounts'
  NODE_OPTIONS: "--max_old_space_size=32768"
  DEBUG: true
  PRIZE_TIERS_TO_COMPUTE: 0,1,2,3,4,5
permissions: write-all
jobs:
  runCLI:
    name: Winners Compute
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node: ["20.11.1"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      # -------------------------------------------------------- #
      # Optimism Mainnet
      # -------------------------------------------------------- #
      # 1. Install
      - name: Install PoolTogether V5 CLI
        run: |
          npm install -g @generationsoftware/pt-v5-cli@${{ env.CLI_VERSION }}
          echo "$(npm -g bin)" >> $GITHUB_PATH
          
      # 2. Find depositors, winners, and output them for each vault to JSON files
      - name: Optimism Mainnet - Compile Winners
        id: compileWinnersOptimism
        uses: chuckbergeron/executable-wrapper@e19cd743c8f0c6af006f6a25bd6715c770569d72
        continue-on-error: true
        with:
          run_command: ptv5 utils compileWinners -o ./${{ env.OUTPUT_DIRECTORY_NAME }} -p ${{ env.PRIZE_POOL_ADDRESS }} -c ${{ env.CHAIN_ID }} -j ${{ env.CONTRACT_JSON_URL }} -s ${{ env.SUBGRAPH_URL }} -r ${{ env.REMOTE_STATUS_URL }}

      # 3. Commit
      - name: Commit Optimism Mainnet
        if: steps.compileWinnersOptimism.outputs.runStatus == 'true'
        continue-on-error: true
        run: |
          git config pull.rebase false
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          ls
          git add ./${{ env.OUTPUT_DIRECTORY_NAME }}
          git commit -m "Add mainnet winner results for Optimism Mainnet draw #${{ steps.compileWinnersOptimism.outputs.drawId }}"

      # 4. Push
      - name: Push changes (if required)
        uses: ad-m/github-push-action@master
        if: steps.compileWinnersOptimism.outputs.runStatus == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
