name: CronJob - Optimism Mainnet
on:
  schedule:
    - cron: "5 */6 * * *" # ie. 6:05am, 12:05pm, 6:05pm, etc.
  push:
env:
  CHAIN_ID: 10
  PRIZE_POOL_ADDRESS: "0xf35fe10ffd0a9672d0095c435fd8767a7fe29b55"
  VAULT_ACCOUNTS_DIRECTORY_NAME: "vaultAccounts"
  OUTPUT_DIRECTORY_NAME: "winners"
  CLI_VERSION: "1.2.0"
  FWC_RPC_URL: ${{ secrets.OPTIMISM_MAINNET_RPC_URL }}
  JSON_RPC_URL: ${{ secrets.OPTIMISM_MAINNET_RPC_URL }}
  CONTRACT_JSON_URL: 'https://raw.githubusercontent.com/GenerationSoftware/pt-v5-mainnet/396f04daedc5a38935460ddf47d2f10e9ac1fec6/deployments/optimism/contracts.json'
  SUBGRAPH_URL: 'https://api.studio.thegraph.com/query/63100/pt-v5-optimism/version/latest?source=pooltogether'
  NODE_OPTIONS: "--max_old_space_size=32768"
permissions: write-all
jobs:
  runCLI:
    name: Winners Test
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node: ["20.11.1"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - name: Testetset
        id: vaultAccountsOptimism
        uses: chuckbergeron/executable-wrapper@e19cd743c8f0c6af006f6a25bd6715c770569d72
        continue-on-error: true
        with:
          working-directory: .
          run_command: node --eval "console.log(buffer.constants.MAX_LENGTH);"  
