name: CronJob - Arbitrum Mainnet
on:
  schedule:
    - cron: "5 */2 * * *" # ie. 2:05am, 4:05pm, 6:05pm, etc.
  push:
env:
  CHAIN_ID: 42161
  PRIZE_POOL_ADDRESS: "0x52e7910c4c287848c8828e8b17b8371f4ebc5d42"
  OUTPUT_DIRECTORY_NAME: "winners/vaultAccounts"
  CLI_VERSION: "2.0.8"
  JSON_RPC_URL: ${{ secrets.ARBITRUM_MAINNET_RPC_URL }}
  CONTRACT_JSON_URL: 'https://raw.githubusercontent.com/GenerationSoftware/pt-v5-mainnet/bc9e4b4c25a033ec3c1c2b89b62422399b7db2f6/deployments/arbitrum/contracts.json'
  SUBGRAPH_URL: 'https://api.studio.thegraph.com/query/63100/pt-v5-arbitrum/version/latest'
  REMOTE_STATUS_URL: 'https://raw.githubusercontent.com/GenerationSoftware/pt-v5-winners/refs/heads/main/winners/vaultAccounts'
  NODE_OPTIONS: "--max_old_space_size=32768"
permissions: write-all
jobs:
  runCLI:
    name: Winners Compute
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node: ["20.11.1"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      # -------------------------------------------------------- #
      # Arbitrum Mainnet
      # -------------------------------------------------------- #
      # 1. Install
      - name: Install PoolTogether V5 CLI
        run: |
          npm install -g @generationsoftware/pt-v5-cli@${{ env.CLI_VERSION }}
          echo "$(npm -g bin)" >> $GITHUB_PATH
          
      # 2. Find depositors, winners, and output them for each vault to JSON files
      - name: Arbitrum Mainnet - Compile Winners
        id: compileWinnersArbitrum
        uses: chuckbergeron/executable-wrapper@e19cd743c8f0c6af006f6a25bd6715c770569d72
        continue-on-error: true
        with:
          run_command: ptv5 utils compileWinners -o ./${{ env.OUTPUT_DIRECTORY_NAME }} -p ${{ env.PRIZE_POOL_ADDRESS }} -c ${{ env.CHAIN_ID }} -j ${{ env.CONTRACT_JSON_URL }} -s ${{ env.SUBGRAPH_URL }} -r ${{ env.REMOTE_STATUS_URL }}

      # 3. Commit
      - name: Commit Arbitrum Mainnet
        if: steps.compileWinnersArbitrum.outputs.runStatus == 'true'
        continue-on-error: true
        run: |
          git config pull.rebase false
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          ls
          git add ./${{ env.OUTPUT_DIRECTORY_NAME }}
          git commit -m "Add mainnet winner results for Arbitrum Mainnet draw #${{ steps.compileWinnersArbitrum.outputs.drawId }}"

      # 4. Push
      - name: Push changes (if required)
        uses: ad-m/github-push-action@master
        if: steps.compileWinnersArbitrum.outputs.runStatus == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
